
package mego.mgym.org;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-06-08T20:03:43.235+06:00
 * Generated source version: 2.5.1
 * 
 */
public final class CgUnitServiceSoap_CgUnitServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://org.mGym.mego/", "CgUnitService");

    private CgUnitServiceSoap_CgUnitServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CgUnitService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CgUnitService ss = new CgUnitService(wsdlURL, SERVICE_NAME);
        CgUnitServiceSoap port = ss.getCgUnitServiceSoap();  
        
        {
        System.out.println("Invoking getCgUnitList...");
        mego.mgym.org.ArrayOfCgUnitSnip _getCgUnitList__return = port.getCgUnitList();
        System.out.println("getCgUnitList.result=" + _getCgUnitList__return);


        }
        {
        System.out.println("Invoking getCgUnit...");
        int _getCgUnit_aID = 0;
        mego.mgym.org.CgUnitSnip _getCgUnit__return = port.getCgUnit(_getCgUnit_aID);
        System.out.println("getCgUnit.result=" + _getCgUnit__return);


        }

        System.exit(0);
    }

}
