package mego.mgym.org;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-06-08T20:03:43.331+06:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://org.mGym.mego/", name = "CgUnitServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public class CgUnitServiceSoap 
{

    @WebResult(name = "GetCgUnitListResult", targetNamespace = "http://org.mGym.mego/")
    @RequestWrapper(localName = "GetCgUnitList", targetNamespace = "http://org.mGym.mego/", className = "mego.mgym.org.GetCgUnitList")
    @WebMethod(operationName = "GetCgUnitList", action = "http://org.mGym.mego/GetCgUnitList")
    @ResponseWrapper(localName = "GetCgUnitListResponse", targetNamespace = "http://org.mGym.mego/", className = "mego.mgym.org.GetCgUnitListResponse")
    public mego.mgym.org.ArrayOfCgUnitSnip getCgUnitList()
    {
    	return new ArrayOfCgUnitSnip();
    }

    @WebResult(name = "GetCgUnitResult", targetNamespace = "http://org.mGym.mego/")
    @RequestWrapper(localName = "GetCgUnit", targetNamespace = "http://org.mGym.mego/", className = "mego.mgym.org.GetCgUnit")
    @WebMethod(operationName = "GetCgUnit", action = "http://org.mGym.mego/GetCgUnit")
    @ResponseWrapper(localName = "GetCgUnitResponse", targetNamespace = "http://org.mGym.mego/", className = "mego.mgym.org.GetCgUnitResponse")
    public mego.mgym.org.CgUnitSnip getCgUnit(   @WebParam(name = "aID", targetNamespace = "http://org.mGym.mego/") int aID    )
    {
    	CgUnitSnip unitSnip = new CgUnitSnip ( );
    	
    	unitSnip.setContact ( "asraf" );
    	unitSnip.setName ( "asrafhaque" );
    	unitSnip.setDescription ( "description " );
    	unitSnip.setContact ( "01913456787" );
    	Location location = new Location ( );
    	location.setLatitude ( "19.09" );
    	location.setLongitude ( "99.09" );
    	unitSnip.setLocation ( location );
    	
    	return unitSnip;
    }
}
