package org.jinouts.ws;

import org.jinouts.jws.WebMethod;
import org.jinouts.jws.WebParam;
import org.jinouts.jws.WebResult;
import org.jinouts.jws.WebService;
import org.jinouts.xml.bind.annotation.XmlSeeAlso;
import org.jinouts.xml.ws.RequestWrapper;
import org.jinouts.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-05-23T21:26:11.105+06:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://ws.jinouts.org/", name = "AndProxyClientRespTestWS")
@XmlSeeAlso({ObjectFactory.class})
public interface AndProxyClientRespTestWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "testPrimitiveResponse", targetNamespace = "http://ws.jinouts.org/", className = "org.jinouts.ws.TestPrimitiveResponse")
    @WebMethod
    @ResponseWrapper(localName = "testPrimitiveResponseResponse", targetNamespace = "http://ws.jinouts.org/", className = "org.jinouts.ws.TestPrimitiveResponseResponse")
    public java.lang.String testPrimitiveResponse(
        @WebParam(name = "user", targetNamespace = "")
        java.lang.String user,
        @WebParam(name = "pass", targetNamespace = "")
        java.lang.String pass
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "testComplexResponseObject", targetNamespace = "http://ws.jinouts.org/", className = "org.jinouts.ws.TestComplexResponseObject")
    @WebMethod
    @ResponseWrapper(localName = "testComplexResponseObjectResponse", targetNamespace = "http://ws.jinouts.org/", className = "org.jinouts.ws.TestComplexResponseObjectResponse")
    public org.jinouts.ws.TestComplexResponse testComplexResponseObject(
        @WebParam(name = "user", targetNamespace = "")
        java.lang.String user
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "testListResponse", targetNamespace = "http://ws.jinouts.org/", className = "org.jinouts.ws.TestListResponse")
    @WebMethod
    @ResponseWrapper(localName = "testListResponseResponse", targetNamespace = "http://ws.jinouts.org/", className = "org.jinouts.ws.TestListResponseResponse")
    public java.util.List<java.lang.String> testListResponse(
        @WebParam(name = "user", targetNamespace = "")
        java.lang.String user
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "testDateResponse", targetNamespace = "http://ws.jinouts.org/", className = "org.jinouts.ws.TestDateResponse")
    @WebMethod
    @ResponseWrapper(localName = "testDateResponseResponse", targetNamespace = "http://ws.jinouts.org/", className = "org.jinouts.ws.TestDateResponseResponse")
    public javax.xml.datatype.XMLGregorianCalendar testDateResponse(
        @WebParam(name = "user", targetNamespace = "")
        java.lang.String user
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "testListOfComplexResponseObject", targetNamespace = "http://ws.jinouts.org/", className = "org.jinouts.ws.TestListOfComplexResponseObject")
    @WebMethod
    @ResponseWrapper(localName = "testListOfComplexResponseObjectResponse", targetNamespace = "http://ws.jinouts.org/", className = "org.jinouts.ws.TestListOfComplexResponseObjectResponse")
    public java.util.List<org.jinouts.ws.TestComplexResponse> testListOfComplexResponseObject(
        @WebParam(name = "user", targetNamespace = "")
        java.lang.String user
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "testArrayResponse", targetNamespace = "http://ws.jinouts.org/", className = "org.jinouts.ws.TestArrayResponse")
    @WebMethod
    @ResponseWrapper(localName = "testArrayResponseResponse", targetNamespace = "http://ws.jinouts.org/", className = "org.jinouts.ws.TestArrayResponseResponse")
    public java.util.List<java.lang.String> testArrayResponse(
        @WebParam(name = "user", targetNamespace = "")
        java.lang.String user
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "testListOfObjResponse", targetNamespace = "http://ws.jinouts.org/", className = "org.jinouts.ws.TestListOfObjResponse")
    @WebMethod
    @ResponseWrapper(localName = "testListOfObjResponseResponse", targetNamespace = "http://ws.jinouts.org/", className = "org.jinouts.ws.TestListOfObjResponseResponse")
    public java.util.List<org.jinouts.ws.MbrDetail> testListOfObjResponse(
        @WebParam(name = "user", targetNamespace = "")
        java.lang.String user
    );
}
