
package org.jinouts.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import org.jinouts.xml.namespace.QName;
import org.jinouts.jws.WebMethod;
import org.jinouts.jws.WebParam;
import org.jinouts.jws.WebResult;
import org.jinouts.jws.WebService;
import org.jinouts.xml.bind.annotation.XmlSeeAlso;
import org.jinouts.xml.ws.RequestWrapper;
import org.jinouts.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-05-23T21:26:11.041+06:00
 * Generated source version: 2.5.1
 * 
 */
public final class AndProxyClientRespTestWS_AndProxyClientRespTestWSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.jinouts.org/", "AndProxyClientRespTestWS");

    private AndProxyClientRespTestWS_AndProxyClientRespTestWSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AndProxyClientRespTestWS_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AndProxyClientRespTestWS_Service ss = new AndProxyClientRespTestWS_Service(wsdlURL, SERVICE_NAME);
        AndProxyClientRespTestWS port = ss.getAndProxyClientRespTestWSPort();  
        
        {
        System.out.println("Invoking testPrimitiveResponse...");
        java.lang.String _testPrimitiveResponse_user = "";
        java.lang.String _testPrimitiveResponse_pass = "";
        java.lang.String _testPrimitiveResponse__return = port.testPrimitiveResponse(_testPrimitiveResponse_user, _testPrimitiveResponse_pass);
        System.out.println("testPrimitiveResponse.result=" + _testPrimitiveResponse__return);


        }
        {
        System.out.println("Invoking testComplexResponseObject...");
        java.lang.String _testComplexResponseObject_user = "";
        org.jinouts.ws.TestComplexResponse _testComplexResponseObject__return = port.testComplexResponseObject(_testComplexResponseObject_user);
        System.out.println("testComplexResponseObject.result=" + _testComplexResponseObject__return);


        }
        {
        System.out.println("Invoking testListResponse...");
        java.lang.String _testListResponse_user = "";
        java.util.List<java.lang.String> _testListResponse__return = port.testListResponse(_testListResponse_user);
        System.out.println("testListResponse.result=" + _testListResponse__return);


        }
        {
        System.out.println("Invoking testDateResponse...");
        java.lang.String _testDateResponse_user = "";
        javax.xml.datatype.XMLGregorianCalendar _testDateResponse__return = port.testDateResponse(_testDateResponse_user);
        System.out.println("testDateResponse.result=" + _testDateResponse__return);


        }
        {
        System.out.println("Invoking testListOfComplexResponseObject...");
        java.lang.String _testListOfComplexResponseObject_user = "";
        java.util.List<org.jinouts.ws.TestComplexResponse> _testListOfComplexResponseObject__return = port.testListOfComplexResponseObject(_testListOfComplexResponseObject_user);
        System.out.println("testListOfComplexResponseObject.result=" + _testListOfComplexResponseObject__return);


        }
        {
        System.out.println("Invoking testArrayResponse...");
        java.lang.String _testArrayResponse_user = "";
        java.util.List<java.lang.String> _testArrayResponse__return = port.testArrayResponse(_testArrayResponse_user);
        System.out.println("testArrayResponse.result=" + _testArrayResponse__return);


        }
        {
        System.out.println("Invoking testListOfObjResponse...");
        java.lang.String _testListOfObjResponse_user = "";
        java.util.List<org.jinouts.ws.MbrDetail> _testListOfObjResponse__return = port.testListOfObjResponse(_testListOfObjResponse_user);
        System.out.println("testListOfObjResponse.result=" + _testListOfObjResponse__return);


        }

        System.exit(0);
    }

}
