package org.jinouts.ws;

import java.net.MalformedURLException;
import java.net.URL;
import org.jinouts.xml.namespace.QName;
import org.jinouts.xml.ws.WebEndpoint;
import org.jinouts.xml.ws.WebServiceClient;
import org.jinouts.xml.ws.WebServiceFeature;
import org.jinouts.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-05-23T21:26:11.128+06:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "AndProxyClientRespTestWS", 
                  wsdlLocation = "http://116.68.194.105:9011/AndProxyClientRespTestWS?WSDL",
                  targetNamespace = "http://ws.jinouts.org/") 
public class AndProxyClientRespTestWS_Service extends org.jinouts.ws.JinosService {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.jinouts.org/", "AndProxyClientRespTestWS");
    public final static QName AndProxyClientRespTestWSPort = new QName("http://ws.jinouts.org/", "AndProxyClientRespTestWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://116.68.194.105:9011/AndProxyClientRespTestWS?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AndProxyClientRespTestWS_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://116.68.194.105:9011/AndProxyClientRespTestWS?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public AndProxyClientRespTestWS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AndProxyClientRespTestWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AndProxyClientRespTestWS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AndProxyClientRespTestWS
     */
    @WebEndpoint(name = "AndProxyClientRespTestWSPort")
    public AndProxyClientRespTestWS getAndProxyClientRespTestWSPort() {
        return super.getPort(AndProxyClientRespTestWSPort, AndProxyClientRespTestWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AndProxyClientRespTestWS
     */
    @WebEndpoint(name = "AndProxyClientRespTestWSPort")
    public AndProxyClientRespTestWS getAndProxyClientRespTestWSPort(WebServiceFeature... features) {
        return super.getPort(AndProxyClientRespTestWSPort, AndProxyClientRespTestWS.class, features);
    }

}
