
package org.jinouts.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import org.jinouts.xml.namespace.QName;
import org.jinouts.jws.WebMethod;
import org.jinouts.jws.WebParam;
import org.jinouts.jws.WebResult;
import org.jinouts.jws.WebService;
import org.jinouts.xml.bind.annotation.XmlSeeAlso;
import org.jinouts.xml.ws.RequestWrapper;
import org.jinouts.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-05-23T20:13:43.711+06:00
 * Generated source version: 2.5.1
 * 
 */
public final class AndProxyClientReqTestWS_AndProxyClientReqTestWSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.jinouts.org/", "AndProxyClientReqTestWS");

    private AndProxyClientReqTestWS_AndProxyClientReqTestWSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AndProxyClientReqTestWS_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AndProxyClientReqTestWS_Service ss = new AndProxyClientReqTestWS_Service(wsdlURL, SERVICE_NAME);
        AndProxyClientReqTestWS port = ss.getAndProxyClientReqTestWSPort();  
        
        {
        System.out.println("Invoking testComplexRequestObject...");
        org.jinouts.ws.TestComplexRequest _testComplexRequestObject_request = null;
        java.lang.String _testComplexRequestObject__return = port.testComplexRequestObject(_testComplexRequestObject_request);
        System.out.println("testComplexRequestObject.result=" + _testComplexRequestObject__return);


        }
        {
        System.out.println("Invoking testListDateArrayRequest...");
        javax.xml.datatype.XMLGregorianCalendar _testListDateArrayRequest_date = null;
        java.util.List<java.lang.String> _testListDateArrayRequest_list = null;
        java.util.List<java.lang.String> _testListDateArrayRequest_array = null;
        java.lang.String _testListDateArrayRequest__return = port.testListDateArrayRequest(_testListDateArrayRequest_date, _testListDateArrayRequest_list, _testListDateArrayRequest_array);
        System.out.println("testListDateArrayRequest.result=" + _testListDateArrayRequest__return);


        }
        {
        System.out.println("Invoking testListOfObjRequest...");
        java.util.List<org.jinouts.ws.MbrDetail> _testListOfObjRequest_mbrList = null;
        java.lang.String _testListOfObjRequest__return = port.testListOfObjRequest(_testListOfObjRequest_mbrList);
        System.out.println("testListOfObjRequest.result=" + _testListOfObjRequest__return);


        }
        {
        System.out.println("Invoking testObjectRequest...");
        org.jinouts.ws.Request _testObjectRequest_request = null;
        java.lang.String _testObjectRequest__return = port.testObjectRequest(_testObjectRequest_request);
        System.out.println("testObjectRequest.result=" + _testObjectRequest__return);


        }
        {
        System.out.println("Invoking testPrimitiveRequest...");
        java.lang.String _testPrimitiveRequest_user = "";
        java.lang.String _testPrimitiveRequest_pass = "";
        java.lang.String _testPrimitiveRequest__return = port.testPrimitiveRequest(_testPrimitiveRequest_user, _testPrimitiveRequest_pass);
        System.out.println("testPrimitiveRequest.result=" + _testPrimitiveRequest__return);


        }

        System.exit(0);
    }

}
