
package org.jinouts.ws.axis;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import org.jinouts.xml.namespace.QName;
import org.jinouts.jws.WebMethod;
import org.jinouts.jws.WebParam;
import org.jinouts.jws.WebResult;
import org.jinouts.jws.WebService;
import org.jinouts.xml.bind.annotation.XmlSeeAlso;
import org.jinouts.xml.ws.Action;
import org.jinouts.xml.ws.RequestWrapper;
import org.jinouts.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-05-29T20:07:16.563+06:00
 * Generated source version: 2.5.1
 * 
 */
public final class ComplexRequestWSPortType_ComplexRequestWSHttpEndpoint_Client {

    private static final QName SERVICE_NAME = new QName("http://axis.ws.jinouts.org", "ComplexRequestWS");

    private ComplexRequestWSPortType_ComplexRequestWSHttpEndpoint_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ComplexRequestWS.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ComplexRequestWS ss = new ComplexRequestWS(wsdlURL, SERVICE_NAME);
        ComplexRequestWSPortType port = ss.getComplexRequestWSHttpEndpoint();  
        
        {
        System.out.println("Invoking testComplexRequest...");
        org.jinouts.ws.axis.model.xsd.ComplexRequest _testComplexRequest_request = null;
        java.lang.String _testComplexRequest__return = port.testComplexRequest(_testComplexRequest_request);
        System.out.println("testComplexRequest.result=" + _testComplexRequest__return);


        }

        System.exit(0);
    }

}
