
package org.jinouts.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import org.jinouts.xml.namespace.QName;
import org.jinouts.jws.WebMethod;
import org.jinouts.jws.WebParam;
import org.jinouts.jws.WebResult;
import org.jinouts.jws.WebService;
import org.jinouts.xml.bind.annotation.XmlSeeAlso;
import org.jinouts.xml.ws.RequestWrapper;
import org.jinouts.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-05-23T18:30:44.056+06:00
 * Generated source version: 2.5.1
 * 
 */
public final class Login_LoginPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.jinouts.org/", "LoginService");

    private Login_LoginPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = LoginService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        LoginService ss = new LoginService(wsdlURL, SERVICE_NAME);
        Login port = ss.getLoginPort();  
        
        {
        System.out.println("Invoking enter...");
        java.lang.String _enter_user = "";
        java.lang.String _enter_pass = "";
        java.lang.String _enter__return = port.enter(_enter_user, _enter_pass);
        System.out.println("enter.result=" + _enter__return);


        }

        System.exit(0);
    }

}
